version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      volumes:
        - ./opt/mysql_data:/var/lib/mysql
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: helloworld

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db